use_frameworks!

platform :ios, '11.0'

target 'SmartCodable_Example' do
  pod 'SmartCodable', :path => '../'
  
  pod 'SnapKit'
  pod 'BTPrint'
  pod 'WCDB.swift'
 
  #对比组
  pod 'HandyJSON', '5.0.0-beta.1'
  pod 'CleanJSON'
  

  target 'SmartCodable_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

