platform :ios, '11.0'
use_frameworks!


target 'SmartCodable_Example' do
  pod 'SmartCodable', :path => '../'
  pod 'SnapKit'


end


post_install do |installer|
  
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
#  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Needed for building for simulator on M1 Macs
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end

  
  # Xocde 14 + iOS 16 Pod工程中设置CODE_SIGN_IDENTITY为空来避免报错
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
  end
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end

  
end
