use_frameworks!

platform :ios, '13.0'

target 'SmartCodable_Example' do
  pod 'SmartCodable', :path => '../'
  
  pod 'SnapKit'
  pod 'BTPrint'
  pod 'BTBubble'
   
  #对比组
  pod 'HandyJSON', '5.0.0-beta.1'
  pod 'CleanJSON'
  

  target 'SmartCodable_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
